
## A Perceptron


In [1]:

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt


In [2]:

def activation_function(z):
    return np.where( z>=0, 1, 0  )


In [3]:

activation_function( -0.7 )


array(0)

In [4]:

activation_function( 1.7 )


array(1)

In [5]:

def fit(X_train, y_train):
    
    ##################
    ## Defining the knobs
    
    weights = np.zeros(  2 )
    bias    = 0
    
    #################
    
    learning_rate = 0.01
    
    for _ in range(1000):
        for idx, x_i in enumerate(X_train):
            
            ## print( x_i )
            ## print( weights )
            ## print( bias )
            linear_product = np.dot(x_i, weights) + bias    ## y = w*x + b   ## Inference Equation 
            
            y_pred  = activation_function(    linear_product    )
            
            
            ## print( linear_product )
            ## input()
            
            loss =  y_pred   -  y_train[idx]
            ## list_losses.append( loss  )
            
            ## 
            
            update = learning_rate * ( y_pred   -  y_train[idx] )
            
            weights = weights - update * x_i
            bias    = bias - update
            
            
      
    return weights, bias


In [6]:

X, y = datasets.make_blobs(n_samples=150, n_features=2, centers=2, cluster_std=1.05, random_state=2)


In [7]:

X.shape


(150, 2)

In [8]:

X[0:2, :]


array([[ -0.53278301,  -1.64847081],
       [ -0.55022637, -11.61661524]])

In [9]:

y.shape


(150,)

In [10]:

y


array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1])

In [11]:

X[:5, :]


array([[ -0.53278301,  -1.64847081],
       [ -0.55022637, -11.61661524],
       [  1.38862276,  -1.4358059 ],
       [  1.37033956,  -0.64022071],
       [ -0.88060639,  -9.7094674 ]])

In [12]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)


In [13]:

print( X_train.shape )
print( X_test.shape )
print( y_train.shape )
print( y_test.shape )


(120, 2)
(30, 2)
(120,)
(30,)


In [14]:

weights, bias = fit(X_train, y_train)


In [15]:
weights



array([0.03534528, 0.03089668])

In [16]:

bias


0.12999999999999998

In [17]:

def predict(X_test, weights, bias):
    ## x * w
    linear_product = np.dot(X_test, weights) + bias    ## y = w*x + b
    y_pred  = activation_function(    linear_product    )
    return y_pred


In [18]:

def accuracy(y_true, y_pred):
    accuracy = np.sum(   y_true == y_pred   ) / len(  y_true  )
    return accuracy


In [19]:

y_pred = predict(X_test, weights, bias)


In [20]:

y_pred


array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0])

In [21]:

y_test


array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0])

In [22]:

print(  accuracy(y_pred, y_test)   )


1.0
