In [20]:

## !pip install pandas
## !pip install scikit-learn


In [53]:

import pandas as pd
import numpy as np
import sklearn

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from collections import Counter

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score, accuracy_score, f1_score


In [6]:

k = 5


In [7]:

df = pd.read_csv("iris.csv", header=None)


In [8]:

df


0            1             2            3          4
0    sepal_length  sepal_width  petal_length  petal_width    species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[151 rows x 5 columns]

In [9]:

X = df.loc[  1:, :3].values


In [11]:

X.shape


(150, 4)

In [12]:

type(X)


numpy.ndarray

In [13]:

X = X.astype(float)


In [14]:

y = df.loc[1:, 4].values


In [15]:

y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [16]:

len(y)


150

In [17]:

y.shape


(150,)

In [22]:

le = LabelEncoder()

y = le.fit_transform(  y  )


In [23]:

y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:

X.shape


(150, 4)

In [25]:

y.shape


(150,)

In [57]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)


In [58]:

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(90, 4)
(60, 4)
(90,)
(60,)


In [59]:

def euclidean_distance(  v1, v2 ):
    return np.sqrt( np.sum(   (v1 - v2)**2   )   )



'''

def euclidean_distance(v1, v2):

    return np.sqrt( np.sum(   (v1 - v2)**2   )   )
    
'''



'\n\ndef euclidean_distance(v1, v2):\n\n    return np.sqrt( np.sum(   (v1 - v2)**2   )   )\n    \n'

In [60]:

def knn_predict( test_x ):
    
    ## calculate distances between test_x and all data samples in X_train
    
    distances = [  euclidean_distance( test_x, x )  for x in X_train   ]
    
    ## sort by distance and return the k closest neighbors
    ## argsort returns the indices of the k nearest neighbors
    
    k_neighbor_indeces =   np.argsort(   distances   )[  :k  ]
    
    ## extract labels from y_train
    
    labels = [    y_train[ i ]  for i in k_neighbor_indeces   ]
    
    ## print( labels )
    
    most_common_label = Counter(labels).most_common(1)
   
    ## print(  most_common_label[0][0] )
    
    return  most_common_label[0][0]




In [61]:

y_pred_list = []

for test_x in X_test:
    
    my_y_pred = knn_predict( test_x )  
    y_pred_list.append(  my_y_pred  )
  


In [62]:

y_pred_list


[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 1]

In [63]:

def print_stats_performance_metrics(y_test, y_pred):
    
    print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print(confmat)
    print('Precision: %.2f' % precision_score(y_test, y_pred, average='weighted'))
    print('Recall: %.2f' % recall_score(y_test, y_pred, average='weighted'))
    print('F1_score: %.2f' % f1_score(y_test, y_pred, average='weighted'))


In [64]:

y_pred = np.array( y_pred_list )


In [65]:

print_stats_performance_metrics(y_test, y_pred)


Accuracy: 0.98
[[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]
Precision: 0.98
Recall: 0.98
F1_score: 0.98
