## KNN in batches

In [1]:
## !pip install scikit-learn

In [2]:
## !pip install pandas

In [3]:

import numpy as np
import sklearn
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import Counter

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score, accuracy_score, f1_score




In [4]:
## !pip install tensorflow

In [5]:
## import tensorflow

In [6]:
k = 5

In [7]:

def euclidean_distance_batches(test_v1, batch_v2):
    mat_mul         = (batch_v2 - test_v1)
    sqr_mat_mul     = np.square(  mat_mul               )
    sum_sqr_mat_mul = np.sum(    sqr_mat_mul, 1         ) 
    temp1           = np.sqrt(     sum_sqr_mat_mul      )
   
    return temp1
 


In [8]:

def euclidean_distance(v1, v2):
    return np.sqrt( np.sum(   (v1 - v2)**2   )   )

In [9]:

'''
start_index = 0
end_index   = start_index + batch_size

for batch_n in range(num_of_batches):
    ## print(batch_n)
    start_index = batch_n * batch_size 
    end_index   = (batch_n + 1)*batch_size
    ## print(start_index)
    ## print(end_index)
    print("************")
    test_x = X_test[ start_index:end_index ,  : ]
    ## print(test_x.shape[0])

    temp_pred = predict(test_x)
    ## print(temp_pred[0][0] )
    ##list_of_pred_labels.append(     temp_pred[0][0]      )
    
'''

def predict_batches(test_x):
    
    concatenated_distances = np.array([])
    
    start_index = 0
    end_index   = start_index + batch_size

    for batch_n in range(num_of_batches):
        start_index = batch_n * batch_size 
        end_index   = (batch_n + 1)*batch_size

        train_X_batch = X_train[ start_index:end_index ,  : ]
        
        distances = euclidean_distance_batches(test_x , train_X_batch) 
        
        
        concatenated_distances = np.concatenate((concatenated_distances, distances))
    ## print(concatenated_distances.size)
    k_neighbor_indices = np.argsort(concatenated_distances )[:k]
    labels = [ y_train[i]  for i in k_neighbor_indices  ]
    most_common_label = Counter(labels).most_common(1)
    
    return most_common_label
    


 

   




In [10]:

def predict(test_x):
    
    ## calculate distances between test_x and all dta samples in x
    ## this distances vector is a vector of 45 distances
    ## distances = [ euclidean_distance(test_x , x)  for x in X_train    ]
    for x in X_train:
        distances = euclidean_distance(test_x , x) 
        
      
    
    ## distances - > [23, 3, 145, 17, ...]
    
    ## sort by distance value and return the k nearest neighbors
    ## np.argsort returns the indices of the k neares neighbors
    k_neighbor_indices = np.argsort(distances)[:k]
    
    
    ## with indices, extract labels from y_train 
    labels = [ y_train[i]  for i in k_neighbor_indices  ]
    ## imagine labels = [ 1, 1, 2, 0, 1]
    
    ## from labels, select the most common label
    most_common_label = Counter(labels).most_common(1)
    
    return most_common_label
    


In [11]:

df = pd.read_csv("iris.csv", header=None)


In [12]:
df

0            1             2            3          4
0    sepal_length  sepal_width  petal_length  petal_width    species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[151 rows x 5 columns]

In [13]:
## n_features = X_train.shape
## n_features[1]

In [14]:
X = df.loc[1:, :3].values

X = X.astype(float)

In [15]:
y = df.loc[1:, 4].values

In [16]:
len(y)

150

In [17]:
X.shape


(150, 4)

In [18]:
y.shape

(150,)

In [19]:

le = LabelEncoder()
y = le.fit_transform(  y  )


In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
## X

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)



## Inference



In [24]:

list_of_pred_labels = []

batch_size = 5

size_of_X = X_train.shape[0]
print(size_of_X)

num_of_batches = int(size_of_X/batch_size)
print(num_of_batches)




105
21


In [25]:



for test_x in X_test:

    temp_pred = predict_batches(test_x)
    ## print(temp_pred[0][0] )
    list_of_pred_labels.append(     temp_pred[0][0]      )
    

    

In [26]:
len(list_of_pred_labels)

45

In [27]:
print(np.array(list_of_pred_labels))
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [28]:

def accuracy(y_test, y_pred):
    
    accuracy_value = np.sum(y_pred == y_test)/len(y_test)
    return accuracy_value
    


In [29]:

def print_stats_performance_metrics(y_test, y_pred):
    
    print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print(confmat)
    print('Precision: %.2f' % precision_score(y_test, y_pred, average='weighted'))
    print('Recall: %.2f' % recall_score(y_test, y_pred, average='weighted'))
    print('F1_score: %.2f' % f1_score(y_test, y_pred, average='weighted'))


In [30]:

y_pred = np.array(list_of_pred_labels)


In [31]:
res = accuracy(y_test, y_pred)

In [32]:
print(res)

1.0


In [33]:
print_stats_performance_metrics(y_test, y_pred)

Accuracy: 1.00
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Precision: 1.00
Recall: 1.00
F1_score: 1.00
