In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

#######################################

## MovieLens dataset

#######################################

data = pd.read_csv('data/ratings.csv')

users  = data['userId'].unique()
movies = data['movieId'].unique()

#print( len(users)  )
#print(len(movies)  )
print(data.head())

#######################################

data_ratings = pd.read_csv('data/ratings.csv')

data_movies  = pd.read_csv('data/movies.csv')

print(data_movies.head())

######################################

ratings_mat = np.zeros(shape=(9724, 610), dtype=np.uint8)

print(ratings_mat.shape)

#####################################
print(data_movies)




   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
   movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
(9724, 610)
      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jum

In [2]:
ratings_array  = data_ratings.rating.values
movieIds_array = data_ratings.movieId.values
userIds_array  = data_ratings.userId.values

################################################

movies_uniques_dict_ref_real = {}
movies_uniques_dict_real_ref = {}
movies_uniques = np.unique(  movieIds_array    )
for idx, res in enumerate(movies_uniques):
    movies_uniques_dict_ref_real[idx] = res
    movies_uniques_dict_real_ref[res] = idx
    

users_uniques_dict_ref_real = {}
users_uniques_dict_real_ref = {}
users_uniques = np.unique(  userIds_array    )
for idx, res in enumerate(users_uniques):
    users_uniques_dict_ref_real[idx] = res
    users_uniques_dict_real_ref[res] = idx
      

## print(  movies_uniques_dict_ref_real  )        

################################################

for i in range(   len(ratings_array)    ):
    u = userIds_array[i]
    m = movieIds_array[i]
    
    ref_u = users_uniques_dict_real_ref[u]
    ref_m = movies_uniques_dict_real_ref[m]
    
    ratings_mat[ref_m, ref_u] = ratings_array[i]

################################################

print(  ratings_mat[:20,:20]  )
print(  ratings_mat.shape  )


[[4 0 0 0 4 0 4 0 0 0 0 0 0 0 2 0 4 3 4 0]
 [0 0 0 0 0 4 0 4 0 0 0 0 0 0 0 0 0 3 3 3]
 [4 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 4 0 0 0 0 5 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 3 0 0 0 0 2 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 2 0 0 3 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 4 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 3 4]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
(9724, 610)


In [3]:
U, S, V = np.linalg.svd(  ratings_mat  )

print(U.shape)
print(S.shape)
print(V.shape)

##print( S[:609]   )

(9724, 9724)
(610,)
(610, 610)


In [4]:

## function  to calculate the cosine similarity
## this is similar to the euclidean distance 
## it sorts by most similar, and returns the top n


def top_cosine_similarity(data, movie_id, k, top_n):
    
    movie_row = np.array(   data[movie_id, : ]   )    ## 1x50
    
    
    ## np argsort
    
    similarity = np.dot(     movie_row,       data.T     )  
    sort_indeces = np.argsort(similarity)
    
    ## sklearn
    
    #movie_row = movie_row.reshape(-1, k)
    #similarity = cosine_similarity(movie_row, data)
    #sort_indeces = np.argsort(  similarity[0]  ) 
    #sort_indeces = sort_indeces.tolist()
    
    
    
    return sort_indeces[:top_n]
                       
                          


In [5]:

k = 200          ## 50 principal components


search_movie_id = 79132
ref_movie_id = movies_uniques_dict_real_ref[search_movie_id]

sliced_matrix = np.array(  U[:, :k]  )

top_indeces = top_cosine_similarity(sliced_matrix, ref_movie_id, k, top_n=10)

print(  top_indeces  )

[6293   43  257 6513 1916 2391 5880 3189 4350  613]


In [6]:
##real_my_id = movies_uniques_dict_ref_real[movie_id]
## print(real_my_id)


print(    data_movies[data_movies.movieId == search_movie_id].title.values[0]    )


print("now recommended movies ")
for ref in top_indeces:
    #print(ref)
    real_movie_id = movies_uniques_dict_ref_real[ref] 
    print(real_movie_id)
    print(   data_movies[data_movies.movieId == real_movie_id].title.values[0]     )
    
    

Inception (2010)
now recommended movies 
48385
Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan (2006)
47
Seven (a.k.a. Se7en) (1995)
296
Pulp Fiction (1994)
54272
Simpsons Movie, The (2007)
2542
Lock, Stock & Two Smoking Barrels (1998)
3175
Galaxy Quest (1999)
33493
Star Wars: Episode III - Revenge of the Sith (2005)
4306
Shrek (2001)
6373
Bruce Almighty (2003)
778
Trainspotting (1996)
