In [11]:
import numpy as np
import pandas as pd


#######################################

## MovieLens dataset

#######################################

data = pd.read_csv('data/ratings.csv')

users  = data['userId'].unique()
movies = data['movieId'].unique()

#print( len(users)  )
#print(len(movies)  )
print(data.head())

#######################################

data_ratings = pd.read_csv('data/ratings.csv')

data_movies  = pd.read_csv('data/movies.csv')

print(data_movies.head())

######################################

ratings_mat = np.zeros(shape=(9724, 610), dtype=np.uint8)

print(ratings_mat.shape)

#####################################





   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
   movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
(9724, 610)


In [12]:
ratings_array  = data_ratings.rating.values
movieIds_array = data_ratings.movieId.values
userIds_array  = data_ratings.userId.values

################################################

movies_uniques_dict_ref_real = {}
movies_uniques_dict_real_ref = {}
movies_uniques = np.unique(  movieIds_array    )
for idx, res in enumerate(movies_uniques):
    movies_uniques_dict_ref_real[idx] = res
    movies_uniques_dict_real_ref[res] = idx
    

users_uniques_dict_ref_real = {}
users_uniques_dict_real_ref = {}
users_uniques = np.unique(  userIds_array    )
for idx, res in enumerate(users_uniques):
    users_uniques_dict_ref_real[idx] = res
    users_uniques_dict_real_ref[res] = idx
      

## print(  movies_uniques_dict_ref_real  )        

################################################

for i in range(   len(ratings_array)    ):
    u = userIds_array[i]
    m = movieIds_array[i]
    
    ref_u = users_uniques_dict_real_ref[u]
    ref_m = movies_uniques_dict_real_ref[m]
    
    ratings_mat[ref_m, ref_u] = ratings_array[i]

################################################


print(  ratings_mat  )


[[4 0 0 ... 2 3 5]
 [0 0 0 ... 2 0 0]
 [4 0 0 ... 2 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
U, S, V = np.linalg.svd(  ratings_mat  )

print(U.shape)
print(S.shape)
print(V.shape)

##print( S[:609]   )

(9724, 9724)
(610,)
(610, 610)


In [14]:
## goal: to recommend similar movies



###################################################

## function  to calculate the cosine similarity
## it sorts by most similar, and returns the top n


def top_cosine_similarity(data, movie_id, top_n):
    index = movie_id
    
    #########################
    
    movie_row = data[index, : ]    ## 1x50
    
    ##magnitude = np.sqrt(    np.einsum('ij, ij -> i', data, data)    )
    
    
    similarity = np.dot(     movie_row,       data.T     )   
                     
    ## returns indeces sorted from smallest to the biggest
    sort_indeces = np.argsort(  similarity )
                     
   
                     
    return sort_indeces[:top_n]
                       
                          
    #########################
    

###################################################


k = 50          ## 50 principal components
movie_id = 3000  ## e.g. the matrix

sliced_matrix = U[:, :k]

top_indeces = top_cosine_similarity(sliced_matrix, movie_id, top_n=10)
print(  top_indeces  )



[ 277  973  906 1644 4522  895 1660 5150  314 3563]


In [15]:
real_my_id = movies_uniques_dict_ref_real[movie_id]
print(real_my_id)
print(    data_movies[data_movies.movieId == real_my_id].title.values[0]    )



for ref in top_indeces:
    real_movie_id = movies_uniques_dict_ref_real[ref] 
    print(real_movie_id)
    print(   data_movies[data_movies.movieId == real_movie_id].title.values[0]     )

4020
Gift, The (2000)
318
Shawshank Redemption, The (1994)
1275
Highlander (1986)
1206
Clockwork Orange, A (1971)
2194
Untouchables, The (1987)
6711
Lost in Translation (2003)
1193
One Flew Over the Cuckoo's Nest (1975)
2231
Rounders (1998)
8360
Shrek 2 (2004)
356
Forrest Gump (1994)
4886
Monsters, Inc. (2001)
