In [1]:

### Singular Value Decomposition for Compression

import numpy as np

X = np.array([[5, 5, 0, 0, 1],
              [4, 5, 1, 1, 0],
              [5, 4, 1, 1, 0],
              [0, 0, 4, 4, 4],
              [0, 0, 5, 5, 5],
              [1, 1, 4, 4, 4]], dtype=np.float32)
             
print(X)

#################################

U, S, V = np.linalg.svd(X, full_matrices=False)

print("\nU=", U, "\n\nS=", S, "\n\nV=", V)


#################################

## calc energy

S_square = np.square(S) 
print(S_square)

energy = np.sum(S_square[:2]) / np.sum(S_square)
print(energy)


#################################

New_X = U[ :, :2]

print(New_X)

#################################


[[5. 5. 0. 0. 1.]
 [4. 5. 1. 1. 0.]
 [5. 4. 1. 1. 0.]
 [0. 0. 4. 4. 4.]
 [0. 0. 5. 5. 5.]
 [1. 1. 4. 4. 4.]]

U= [[-2.7171865e-01  5.5085099e-01 -7.8405428e-01  9.8120967e-18
  -3.9183814e-02]
 [-2.8768569e-01  4.7328541e-01  4.3731007e-01 -7.0710677e-01
  -1.9591907e-02]
 [-2.8768569e-01  4.7328541e-01  4.3731007e-01  7.0710677e-01
  -1.9591907e-02]
 [-4.4837394e-01 -2.9141220e-01 -1.2559660e-02 -4.9805911e-17
   5.6041032e-01]
 [-5.6046742e-01 -3.6426526e-01 -1.5699575e-02  1.8978022e-16
  -7.3828852e-01]
 [-4.9545929e-01 -1.7593963e-01 -4.8728533e-02 -3.0966167e-16
   3.7224624e-01]] 

S= [1.3737926e+01 1.0882694e+01 1.3551202e+00 1.0000000e+00 8.3796103e-17] 

V= [[-3.2342756e-01 -3.2342756e-01 -5.2067840e-01 -5.2067840e-01
  -4.9857518e-01]
 [ 6.2832636e-01  6.2832636e-01 -2.5215840e-01 -2.5215840e-01
  -2.8852072e-01]
 [-2.4506586e-02 -2.4506586e-02  4.0658349e-01  4.0658349e-01
  -8.1742191e-01]
 [ 7.0710677e-01 -7.0710677e-01 -1.6966903e-19 -1.3894755e-16
   1.6572781e-16]
 [ 0